ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3

patchedDependencies:
  '@nuxt/vite-builder': patches/@nuxt__vite-builder.patch
